version: '3.3'
services:
  # axonserver:
  #   image: axoniq/axonserver
  #   hostname: axonserver
  #   volumes:
  #     - axonserver-data:/data
  #     - axonserver-events:/eventdata
  #     - axonserver-config:/config:ro
  #   ports:
  #     - '8024:8024'
  #     - '8124:8124'
  #     - '8224:8224'
  #   networks:
  #     - payroll-wallet-network

  mysql-master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    volumes:
      - payroll-wallet-mysql-volume:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@911wallet
      - MYSQL_DATABASE=payroll_wallet_db
    networks:
      - payroll-wallet-network

  # zookeeper:
  #   image: 'bitnami/zookeeper:latest'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - payroll-wallet-network
      
  # kafka:
  #     image: 'bitnami/kafka:latest'
  #     ports:
  #     - '9092:9092'
  #     environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     networks:
  #       - payroll-wallet-network
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  payroll-wallet-mysql-volume:

networks:
  payroll-wallet-network: