name: remote ssh command
on:
 push:
  branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
    - name: Install Dependencies
        working-directory: ./deploy
        run: touch text.txt
    - name: Build
        working-directory: ./deploy
        run: echo "ok2"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
      
