name: remote ssh command
defaults:
  run:
    working-directory: /home/deployment/deploy

on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        TARGET: /home/deployment/deploy/
        script: cd /home/deployment/deploy && touch text.txt
